#1.A. Test case 1
nama = input("Masukkan nama mahasiswa: ")
nim = input("Masukkan NIM-nya: ")
c = int(nim[2:4])
d = int(nim[0:2])
if c == 20 or c == 21 or c == 22 and d == 71:
    print(nama,"merupakan mahasiswa Informatika angkatan 20 hingga 22")
else:
    print(nama,"bukan mahasiswa Informatika angkatan 20 hingga 22")

#1.B. Test case 2
nama = input("Masukkan nama mahasiswa: ")
nim = input("Masukkan NIM-nya: ")
c = int(nim[2:4])
d = int(nim[0:2])
if c == 20 or c == 21 or c == 22 and d == 71:
    print(nama,"merupakan mahasiswa Informatika angkatan 20 hingga 22")
else:
    print(nama,"bukan mahasiswa Informatika angkatan 20 hingga 22")

#1.C. Test case 3
nama = input("Masukkan nama mahasiswa: ")
nim = input("Masukkan NIM-nya: ")
c = int(nim[2:4])
d = int(nim[0:2])
if c == 20 or c == 21 or c == 22 and d == 71:
    print(nama,"merupakan mahasiswa Informatika angkatan 20 hingga 22")
else:
    print(nama,"bukan mahasiswa Informatika angkatan 20 hingga 22")



